name: CI

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: /tmp/.cache/ms-playwright

    steps:
      - uses: actions/checkout@v2

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Browser cache
        uses: actions/cache@v3
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}/**
          key: ${{ runner.os }}-browsers

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm run test

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Run linters
        run: pnpm run lint
