name: Create release and publish to NPM

on:
  push:
    branches:
      - master

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Prepare workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/prepare-workflow

      - name: Build module
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build
        shell: bash

      - name: Publich package
        if: ${{ steps.release.outputs.release_created }}
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - if: ${{ steps.publish.outputs.id }}
        run: echo $PACKAGE_INFO
        env:
          PACKAGE_INFO: ${{ steps.publish.outputs.id }}
